//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTrayMenu.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemTrayMenu.Resources.Languages.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add content of folders to main menu.
        /// </summary>
        internal static string Add_content_of_folders_to_main_menu {
            get {
                return ResourceManager.GetString("Add content of folders to main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        internal static string Add_folder {
            get {
                return ResourceManager.GetString("Add folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sample &apos;Start Menu&apos; folder.
        /// </summary>
        internal static string Add_sample__Start_Menu__folder {
            get {
                return ResourceManager.GetString("Add sample \'Start Menu\' folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Show hidden files, folders or drives.
        /// </summary>
        internal static string Always_Show_hidden_files__folders_or_drives {
            get {
                return ResourceManager.GetString("Always Show hidden files, folders or drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow when clicking.
        /// </summary>
        internal static string Arrow_when_clicking {
            get {
                return ResourceManager.GetString("Arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow while mouse hovers.
        /// </summary>
        internal static string Arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background of arrow when clicking.
        /// </summary>
        internal static string Background_of_arrow_when_clicking {
            get {
                return ResourceManager.GetString("Background of arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background of arrow while mouse hovers.
        /// </summary>
        internal static string Background_of_arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Background of arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border of menu.
        /// </summary>
        internal static string Border_of_menu {
            get {
                return ResourceManager.GetString("Border of menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border of opened folder.
        /// </summary>
        internal static string Border_of_opened_folder {
            get {
                return ResourceManager.GetString("Border of opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border of selected item.
        /// </summary>
        internal static string Border_of_selected_item {
            get {
                return ResourceManager.GetString("Border of selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        internal static string Bottom_left {
            get {
                return ResourceManager.GetString("Bottom left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        internal static string Bottom_right {
            get {
                return ResourceManager.GetString("Bottom right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date.
        /// </summary>
        internal static string By_date {
            get {
                return ResourceManager.GetString("By date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name.
        /// </summary>
        internal static string By_name {
            get {
                return ResourceManager.GetString("By name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache main menu.
        /// </summary>
        internal static string Cache_main_menu {
            get {
                return ResourceManager.GetString("Cache main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        internal static string Change_folder {
            get {
                return ResourceManager.GetString("Change folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to relative folder.
        /// </summary>
        internal static string Change_to_relative_folder {
            get {
                return ResourceManager.GetString("Change to relative folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache if more than this number of items.
        /// </summary>
        internal static string Clear_cache_if_more_than_this_number_of_items {
            get {
                return ResourceManager.GetString("Clear cache if more than this number of items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors Dark Mode.
        /// </summary>
        internal static string Colors_Dark_Mode {
            get {
                return ResourceManager.GetString("Colors Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors Light Mode.
        /// </summary>
        internal static string Colors_Light_Mode {
            get {
                return ResourceManager.GetString("Colors Light Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy row item via drag drop.
        /// </summary>
        internal static string Copy_row_item_via_drag_drop {
            get {
                return ResourceManager.GetString("Copy row item via drag drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn’t register the hot key..
        /// </summary>
        internal static string Could_not_register_the_hot_key_ {
            get {
                return ResourceManager.GetString("Could not register the hot key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom (drag it to the appropriate place).
        /// </summary>
        internal static string Custom__drag_it_to_the_appropriate_place_ {
            get {
                return ResourceManager.GetString("Custom (drag it to the appropriate place)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode always active.
        /// </summary>
        internal static string Dark_Mode_always_active {
            get {
                return ResourceManager.GetString("Dark Mode always active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string Drag {
            get {
                return ResourceManager.GetString("Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string element {
            get {
                return ResourceManager.GetString("element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fading.
        /// </summary>
        internal static string Fading {
            get {
                return ResourceManager.GetString("Fading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter menu by file type e.g.: *.exe|*.dll.
        /// </summary>
        internal static string Filter_menu_by_file_type_e_g_____exe___dll {
            get {
                return ResourceManager.GetString("Filter menu by file type e.g.: *.exe|*.dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder empty.
        /// </summary>
        internal static string Folder_empty {
            get {
                return ResourceManager.GetString("Folder empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder inaccessible.
        /// </summary>
        internal static string Folder_inaccessible {
            get {
                return ResourceManager.GetString("Folder inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder paths.
        /// </summary>
        internal static string Folder_paths {
            get {
                return ResourceManager.GetString("Folder paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate shortcuts to drives.
        /// </summary>
        internal static string Generate_shortcuts_to_drives {
            get {
                return ResourceManager.GetString("Generate shortcuts to drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / FAQ.
        /// </summary>
        internal static string HelpFAQ {
            get {
                return ResourceManager.GetString("HelpFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files and folders.
        /// </summary>
        internal static string Hidden_files_and_folders {
            get {
                return ResourceManager.GetString("Hidden files and folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        internal static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an item was clicked.
        /// </summary>
        internal static string If_an_item_was_clicked {
            get {
                return ResourceManager.GetString("If an item was clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the focus is lost and if the mouse is still on the menu.
        /// </summary>
        internal static string If_the_focus_is_lost_and_if_the_mouse_is_still_on_the_menu {
            get {
                return ResourceManager.GetString("If the focus is lost and if the mouse is still on the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the focus is lost and the Enter key was pressed.
        /// </summary>
        internal static string If_the_focus_is_lost_and_the_Enter_key_was_pressed {
            get {
                return ResourceManager.GetString("If the focus is lost and the Enter key was pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on startup.
        /// </summary>
        internal static string Launch_on_startup {
            get {
                return ResourceManager.GetString("Launch on startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        internal static string Log_File {
            get {
                return ResourceManager.GetString("Log File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu appears at.
        /// </summary>
        internal static string Main_menu_appears_at {
            get {
                return ResourceManager.GetString("Main menu appears at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your root folder for the SystemTrayMenu does not exist or is empty! Put some files, folders or shortcuts into the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderEmpty {
            get {
                return ResourceManager.GetString("MessageRootFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to the root folder for the SystemTrayMenu. Grant access to the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderNoAccess {
            get {
                return ResourceManager.GetString("MessageRootFolderNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds until a menu opens when the mouse is on it.
        /// </summary>
        internal static string Milliseconds_until_a_menu_opens_when_the_mouse_is_on_it {
            get {
                return ResourceManager.GetString("Milliseconds until a menu opens when the mouse is on it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds until the menu closes if in this case the menu is not reactivated.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_menu_is_not_reactivated {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the menu is not reactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds until the menu closes if in this case the mouse then leaves the menu.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_mouse_then_leaves_the_menu {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the mouse then leaves the menu" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse location.
        /// </summary>
        internal static string Mouse_location {
            get {
                return ResourceManager.GetString("Mouse location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse location (Above Taskbar icon).
        /// </summary>
        internal static string Mouse_location__Above_Taskbar_icon_ {
            get {
                return ResourceManager.GetString("Mouse location (Above Taskbar icon)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show hidden files, folders or drives.
        /// </summary>
        internal static string Never_show_hidden_files__folders_or_drives {
            get {
                return ResourceManager.GetString("Never show hidden files, folders or drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to the previous one.
        /// </summary>
        internal static string Next_to_the_previous_one {
            get {
                return ResourceManager.GetString("Next to the previous one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset by pixels.
        /// </summary>
        internal static string Offset_by_pixels {
            get {
                return ResourceManager.GetString("Offset by pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Files.
        /// </summary>
        internal static string Only_Files {
            get {
                return ResourceManager.GetString("Only Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the assembly location.
        /// </summary>
        internal static string Open_the_assembly_location {
            get {
                return ResourceManager.GetString("Open the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened folder.
        /// </summary>
        internal static string Opened_folder {
            get {
                return ResourceManager.GetString("Opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping.
        /// </summary>
        internal static string Overlapping {
            get {
                return ResourceManager.GetString("Overlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels maximum menu height.
        /// </summary>
        internal static string Pixels_maximum_menu_height {
            get {
                return ResourceManager.GetString("Pixels maximum menu height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels maximum menu width.
        /// </summary>
        internal static string Pixels_maximum_menu_width {
            get {
                return ResourceManager.GetString("Pixels maximum menu width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with Shortcut.
        /// </summary>
        internal static string Problem_with_Shortcut {
            get {
                return ResourceManager.GetString("Problem with Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder.
        /// </summary>
        internal static string Remove_folder {
            get {
                return ResourceManager.GetString("Remove folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round corners.
        /// </summary>
        internal static string Round_corners {
            get {
                return ResourceManager.GetString("Round corners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height in percent.
        /// </summary>
        internal static string Row_height_in_percent {
            get {
                return ResourceManager.GetString("Row height in percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll via swipe.
        /// </summary>
        internal static string Scroll_via_swipe {
            get {
                return ResourceManager.GetString("Scroll via swipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollbar.
        /// </summary>
        internal static string Scrollbar {
            get {
                return ResourceManager.GetString("Scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search field.
        /// </summary>
        internal static string Search_field {
            get {
                return ResourceManager.GetString("Search field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string Select_Folder {
            get {
                return ResourceManager.GetString("Select Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item.
        /// </summary>
        internal static string Selected_item {
            get {
                return ResourceManager.GetString("Selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send hotkey to other instance.
        /// </summary>
        internal static string Send_hotkey_to_other_instance {
            get {
                return ResourceManager.GetString("Send hotkey to other instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as SystemTrayMenu folder.
        /// </summary>
        internal static string Set_as_SystemTrayMenu_folder {
            get {
                return ResourceManager.GetString("Set as SystemTrayMenu folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set by context menu .
        /// </summary>
        internal static string Set_by_context_menu_ {
            get {
                return ResourceManager.GetString("Set by context menu ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Taskbar.
        /// </summary>
        internal static string Show_in_Taskbar {
            get {
                return ResourceManager.GetString("Show in Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only as search result.
        /// </summary>
        internal static string Show_only_as_search_result {
            get {
                return ResourceManager.GetString("Show only as search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click to open a directory instead of double click.
        /// </summary>
        internal static string Single_click_to_open_a_directory_instead_of_double_click {
            get {
                return ResourceManager.GetString("Single click to open a directory instead of double click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click to open an item instead of double click.
        /// </summary>
        internal static string Single_click_to_open_an_item_instead_of_double_click {
            get {
                return ResourceManager.GetString("Single click to open an item instead of double click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and location.
        /// </summary>
        internal static string Size_and_location {
            get {
                return ResourceManager.GetString("Size and location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the icons in percent.
        /// </summary>
        internal static string Size_of_the_icons_in_percent {
            get {
                return ResourceManager.GetString("Size of the icons in percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider while dragging.
        /// </summary>
        internal static string Slider_while_dragging {
            get {
                return ResourceManager.GetString("Slider while dragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider while mouse hovers 1.
        /// </summary>
        internal static string Slider_while_mouse_hovers_1 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider while mouse hovers 2.
        /// </summary>
        internal static string Slider_while_mouse_hovers_2 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stays open.
        /// </summary>
        internal static string Stays_open {
            get {
                return ResourceManager.GetString("Stays open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store config at the assembly location.
        /// </summary>
        internal static string Store_config_at_the_assembly_location {
            get {
                return ResourceManager.GetString("Store config at the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub menu appears at.
        /// </summary>
        internal static string Sub_menu_appears_at {
            get {
                return ResourceManager.GetString("Sub menu appears at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support SystemTrayMenu.
        /// </summary>
        internal static string Support_SystemTrayMenu {
            get {
                return ResourceManager.GetString("Support SystemTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string System_Info {
            get {
                return ResourceManager.GetString("System Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTrayMenu.
        /// </summary>
        internal static string SystemTrayMenu {
            get {
                return ResourceManager.GetString("SystemTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Task Manager&quot;.
        /// </summary>
        internal static string Task_Manager {
            get {
                return ResourceManager.GetString("Task Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the FAQ and then choose a root directory for the SystemTrayMenu..
        /// </summary>
        internal static string TextFirstStart {
            get {
                return ResourceManager.GetString("TextFirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly..
        /// </summary>
        internal static string The_item_that_this_shortcut_refers_to_has_been_changed_or_moved__so_this_shortcut_will_no_longer_work_properly_ {
            get {
                return ResourceManager.GetString("The item that this shortcut refers to has been changed or moved, so this shortcut" +
                        " will no longer work properly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until a menu opens.
        /// </summary>
        internal static string Time_until_a_menu_opens {
            get {
                return ResourceManager.GetString("Time until a menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use icon from folder.
        /// </summary>
        internal static string Use_icon_from_folder {
            get {
                return ResourceManager.GetString("Use icon from folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use operating system settings.
        /// </summary>
        internal static string Use_operating_system_settings {
            get {
                return ResourceManager.GetString("Use operating system settings", resourceCulture);
            }
        }
    }
}
