//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTrayMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemTrayMenu.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folder.
        /// </summary>
        internal static string Add_folder {
            get {
                return ResourceManager.GetString("Add folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folders to main menu.
        /// </summary>
        internal static string Add_folders_to_main_menu {
            get {
                return ResourceManager.GetString("Add folders to main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add sample &apos;Start Menu&apos; folder.
        /// </summary>
        internal static string Add_sample__Start_Menu__folder {
            get {
                return ResourceManager.GetString("Add sample \'Start Menu\' folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appear at mouse location.
        /// </summary>
        internal static string Appear_at_mouse_location {
            get {
                return ResourceManager.GetString("Appear at mouse location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrow.
        /// </summary>
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrow when clicking.
        /// </summary>
        internal static string Arrow_when_clicking {
            get {
                return ResourceManager.GetString("Arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrow while mouse hovers.
        /// </summary>
        internal static string Arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autostart.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background of arrow when clicking.
        /// </summary>
        internal static string Background_of_arrow_when_clicking {
            get {
                return ResourceManager.GetString("Background of arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background of arrow while mouse hovers.
        /// </summary>
        internal static string Background_of_arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Background of arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Border of menu.
        /// </summary>
        internal static string Border_of_menu {
            get {
                return ResourceManager.GetString("Border of menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Border of opened folder.
        /// </summary>
        internal static string Border_of_opened_folder {
            get {
                return ResourceManager.GetString("Border of opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Border of selected item.
        /// </summary>
        internal static string Border_of_selected_item {
            get {
                return ResourceManager.GetString("Border of selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom left.
        /// </summary>
        internal static string Bottom_left {
            get {
                return ResourceManager.GetString("Bottom left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom right.
        /// </summary>
        internal static string Bottom_right {
            get {
                return ResourceManager.GetString("Bottom right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string buttonDetails {
            get {
                return ResourceManager.GetString("buttonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System Info.
        /// </summary>
        internal static string buttonSystemInfo {
            get {
                return ResourceManager.GetString("buttonSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cache main menu.
        /// </summary>
        internal static string Cache_main_menu {
            get {
                return ResourceManager.GetString("Cache main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change folder.
        /// </summary>
        internal static string Change_folder {
            get {
                return ResourceManager.GetString("Change folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change to relative folder.
        /// </summary>
        internal static string Change_to_relative_folder {
            get {
                return ResourceManager.GetString("Change to relative folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear cache if more than this number of items.
        /// </summary>
        internal static string Clear_cache_if_more_than_this_number_of_items {
            get {
                return ResourceManager.GetString("Clear cache if more than this number of items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors Dark Mode.
        /// </summary>
        internal static string Colors_Dark_Mode {
            get {
                return ResourceManager.GetString("Colors Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors Light Mode.
        /// </summary>
        internal static string Colors_Light_Mode {
            get {
                return ResourceManager.GetString("Colors Light Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn’t register the hot key..
        /// </summary>
        internal static string Could_not_register_the_hot_key_ {
            get {
                return ResourceManager.GetString("Could not register the hot key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customize.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark Mode always active.
        /// </summary>
        internal static string Dark_Mode_always_active {
            get {
                return ResourceManager.GetString("Dark Mode always active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deactivated.
        /// </summary>
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expert.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder empty.
        /// </summary>
        internal static string Folder_empty {
            get {
                return ResourceManager.GetString("Folder empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder inaccessible.
        /// </summary>
        internal static string Folder_inaccessible {
            get {
                return ResourceManager.GetString("Folder inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder paths.
        /// </summary>
        internal static string Folder_paths {
            get {
                return ResourceManager.GetString("Folder paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help / FAQ.
        /// </summary>
        internal static string HelpFAQ {
            get {
                return ResourceManager.GetString("HelpFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkey.
        /// </summary>
        internal static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If an item was clicked.
        /// </summary>
        internal static string If_an_item_was_clicked {
            get {
                return ResourceManager.GetString("If an item was clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the focus is lost and if the mouse is still on the menu.
        /// </summary>
        internal static string If_the_focus_is_lost_and_if_the_mouse_is_still_on_the_menu {
            get {
                return ResourceManager.GetString("If the focus is lost and if the mouse is still on the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the focus is lost and the Enter key was pressed.
        /// </summary>
        internal static string If_the_focus_is_lost_and_the_Enter_key_was_pressed {
            get {
                return ResourceManager.GetString("If the focus is lost and the Enter key was pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch on startup.
        /// </summary>
        internal static string Launch_on_startup {
            get {
                return ResourceManager.GetString("Launch on startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log File.
        /// </summary>
        internal static string Log_File {
            get {
                return ResourceManager.GetString("Log File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main menu appears at.
        /// </summary>
        internal static string Main_menu_appears_at {
            get {
                return ResourceManager.GetString("Main menu appears at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your root folder for the SystemTrayMenu does not exist or is empty! Put some files, folders or shortcuts into the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderEmpty {
            get {
                return ResourceManager.GetString("MessageRootFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no access to the root folder for the SystemTrayMenu. Grant access to the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderNoAccess {
            get {
                return ResourceManager.GetString("MessageRootFolderNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Milliseconds until a menu opens when the mouse is on it.
        /// </summary>
        internal static string Milliseconds_until_a_menu_opens_when_the_mouse_is_on_it {
            get {
                return ResourceManager.GetString("Milliseconds until a menu opens when the mouse is on it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Milliseconds until the menu closes if in this case the menu is not reactivated.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_menu_is_not_reactivated {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the menu is not reactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Milliseconds until the menu closes if in this case the mouse then leaves the menu.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_mouse_then_leaves_the_menu {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the mouse then leaves the menu" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mouse location (Above Taskbar icon).
        /// </summary>
        internal static string Mouse_location__Above_Taskbar_icon_ {
            get {
                return ResourceManager.GetString("Mouse location (Above Taskbar icon)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only Files.
        /// </summary>
        internal static string Only_Files {
            get {
                return ResourceManager.GetString("Only Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Folder.
        /// </summary>
        internal static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open the assembly location.
        /// </summary>
        internal static string Open_the_assembly_location {
            get {
                return ResourceManager.GetString("Open the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened folder.
        /// </summary>
        internal static string Opened_folder {
            get {
                return ResourceManager.GetString("Opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pixels maximum menu height.
        /// </summary>
        internal static string Pixels_maximum_menu_height {
            get {
                return ResourceManager.GetString("Pixels maximum menu height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pixels maximum menu width.
        /// </summary>
        internal static string Pixels_maximum_menu_width {
            get {
                return ResourceManager.GetString("Pixels maximum menu width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem with Shortcut.
        /// </summary>
        internal static string Problem_with_Shortcut {
            get {
                return ResourceManager.GetString("Problem with Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove folder.
        /// </summary>
        internal static string Remove_folder {
            get {
                return ResourceManager.GetString("Remove folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round corners.
        /// </summary>
        internal static string Round_corners {
            get {
                return ResourceManager.GetString("Round corners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Row height in percentage.
        /// </summary>
        internal static string Row_height_in_percentage {
            get {
                return ResourceManager.GetString("Row height in percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scrollbar.
        /// </summary>
        internal static string Scrollbar {
            get {
                return ResourceManager.GetString("Scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search field.
        /// </summary>
        internal static string Search_field {
            get {
                return ResourceManager.GetString("Search field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Folder.
        /// </summary>
        internal static string Select_Folder {
            get {
                return ResourceManager.GetString("Select Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected item.
        /// </summary>
        internal static string Selected_item {
            get {
                return ResourceManager.GetString("Selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as SystemTrayMenu folder.
        /// </summary>
        internal static string Set_as_SystemTrayMenu_folder {
            get {
                return ResourceManager.GetString("Set as SystemTrayMenu folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set by context menu .
        /// </summary>
        internal static string Set_by_context_menu_ {
            get {
                return ResourceManager.GetString("Set by context menu ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in Taskbar.
        /// </summary>
        internal static string Show_in_Taskbar {
            get {
                return ResourceManager.GetString("Show in Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single click to open an item instead of double click.
        /// </summary>
        internal static string Single_click_to_start_item {
            get {
                return ResourceManager.GetString("Single click to start item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider while dragging.
        /// </summary>
        internal static string Slider_while_dragging {
            get {
                return ResourceManager.GetString("Slider while dragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider while mouse hovers 1.
        /// </summary>
        internal static string Slider_while_mouse_hovers_1 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider while mouse hovers 2.
        /// </summary>
        internal static string Slider_while_mouse_hovers_2 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stays open.
        /// </summary>
        internal static string Stays_open {
            get {
                return ResourceManager.GetString("Stays open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Store config at the assembly location.
        /// </summary>
        internal static string Store_config_at_the_assembly_location {
            get {
                return ResourceManager.GetString("Store config at the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SystemTrayMenu.
        /// </summary>
        internal static string SystemTrayMenu {
            get {
                return ResourceManager.GetString("SystemTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Manger.
        /// </summary>
        internal static string Task_Manger {
            get {
                return ResourceManager.GetString("Task Manger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read the FAQ and then choose a root directory for the SystemTrayMenu..
        /// </summary>
        internal static string TextFirstStart {
            get {
                return ResourceManager.GetString("TextFirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The item that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly..
        /// </summary>
        internal static string The_item_that_this_shortcut_refers_to_has_been_changed_or_moved__so_this_shortcut_will_no_longer_work_properly_ {
            get {
                return ResourceManager.GetString("The item that this shortcut refers to has been changed or moved, so this shortcut" +
                        " will no longer work properly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time until a menu opens.
        /// </summary>
        internal static string Time_until_a_menu_opens {
            get {
                return ResourceManager.GetString("Time until a menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update the position every time the menu opens.
        /// </summary>
        internal static string Update_the_position_every_time_the_menu_opens {
            get {
                return ResourceManager.GetString("Update the position every time the menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use icon from folder.
        /// </summary>
        internal static string Use_icon_from_folder {
            get {
                return ResourceManager.GetString("Use icon from folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
