//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTrayMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemTrayMenu.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activated ähnelt.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add folder ähnelt.
        /// </summary>
        internal static string Add_folder {
            get {
                return ResourceManager.GetString("Add folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add folders to main menu ähnelt.
        /// </summary>
        internal static string Add_folders_to_main_menu {
            get {
                return ResourceManager.GetString("Add folders to main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add sample &apos;Start Menu&apos; folder ähnelt.
        /// </summary>
        internal static string Add_sample__Start_Menu__folder {
            get {
                return ResourceManager.GetString("Add sample \'Start Menu\' folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appear at mouse location ähnelt.
        /// </summary>
        internal static string Appear_at_mouse_location {
            get {
                return ResourceManager.GetString("Appear at mouse location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow ähnelt.
        /// </summary>
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow when clicking ähnelt.
        /// </summary>
        internal static string Arrow_when_clicking {
            get {
                return ResourceManager.GetString("Arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow while mouse hovers ähnelt.
        /// </summary>
        internal static string Arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autostart ähnelt.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background ähnelt.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background of arrow when clicking ähnelt.
        /// </summary>
        internal static string Background_of_arrow_when_clicking {
            get {
                return ResourceManager.GetString("Background of arrow when clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background of arrow while mouse hovers ähnelt.
        /// </summary>
        internal static string Background_of_arrow_while_mouse_hovers {
            get {
                return ResourceManager.GetString("Background of arrow while mouse hovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border of menu ähnelt.
        /// </summary>
        internal static string Border_of_menu {
            get {
                return ResourceManager.GetString("Border of menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border of opened folder ähnelt.
        /// </summary>
        internal static string Border_of_opened_folder {
            get {
                return ResourceManager.GetString("Border of opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border of selected item ähnelt.
        /// </summary>
        internal static string Border_of_selected_item {
            get {
                return ResourceManager.GetString("Border of selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom left ähnelt.
        /// </summary>
        internal static string Bottom_left {
            get {
                return ResourceManager.GetString("Bottom left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom right ähnelt.
        /// </summary>
        internal static string Bottom_right {
            get {
                return ResourceManager.GetString("Bottom right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        internal static string buttonDetails {
            get {
                return ResourceManager.GetString("buttonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Info ähnelt.
        /// </summary>
        internal static string buttonSystemInfo {
            get {
                return ResourceManager.GetString("buttonSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache main menu ähnelt.
        /// </summary>
        internal static string Cache_main_menu {
            get {
                return ResourceManager.GetString("Cache main menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change folder ähnelt.
        /// </summary>
        internal static string Change_folder {
            get {
                return ResourceManager.GetString("Change folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change to relative folder ähnelt.
        /// </summary>
        internal static string Change_to_relative_folder {
            get {
                return ResourceManager.GetString("Change to relative folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear cache if more than this number of items ähnelt.
        /// </summary>
        internal static string Clear_cache_if_more_than_this_number_of_items {
            get {
                return ResourceManager.GetString("Clear cache if more than this number of items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click ähnelt.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors Dark Mode ähnelt.
        /// </summary>
        internal static string Colors_Dark_Mode {
            get {
                return ResourceManager.GetString("Colors Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors Light Mode ähnelt.
        /// </summary>
        internal static string Colors_Light_Mode {
            get {
                return ResourceManager.GetString("Colors Light Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn’t register the hot key. ähnelt.
        /// </summary>
        internal static string Could_not_register_the_hot_key_ {
            get {
                return ResourceManager.GetString("Could not register the hot key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize ähnelt.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark Mode always active ähnelt.
        /// </summary>
        internal static string Dark_Mode_always_active {
            get {
                return ResourceManager.GetString("Dark Mode always active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deactivated ähnelt.
        /// </summary>
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expert ähnelt.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder empty ähnelt.
        /// </summary>
        internal static string Folder_empty {
            get {
                return ResourceManager.GetString("Folder empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder inaccessible ähnelt.
        /// </summary>
        internal static string Folder_inaccessible {
            get {
                return ResourceManager.GetString("Folder inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder paths ähnelt.
        /// </summary>
        internal static string Folder_paths {
            get {
                return ResourceManager.GetString("Folder paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folders ähnelt.
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help / FAQ ähnelt.
        /// </summary>
        internal static string HelpFAQ {
            get {
                return ResourceManager.GetString("HelpFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey ähnelt.
        /// </summary>
        internal static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons ähnelt.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If an item was clicked ähnelt.
        /// </summary>
        internal static string If_an_item_was_clicked {
            get {
                return ResourceManager.GetString("If an item was clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the focus is lost and if the mouse is still on the menu ähnelt.
        /// </summary>
        internal static string If_the_focus_is_lost_and_if_the_mouse_is_still_on_the_menu {
            get {
                return ResourceManager.GetString("If the focus is lost and if the mouse is still on the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the focus is lost and the Enter key was pressed ähnelt.
        /// </summary>
        internal static string If_the_focus_is_lost_and_the_Enter_key_was_pressed {
            get {
                return ResourceManager.GetString("If the focus is lost and the Enter key was pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch on startup ähnelt.
        /// </summary>
        internal static string Launch_on_startup {
            get {
                return ResourceManager.GetString("Launch on startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading ähnelt.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log File ähnelt.
        /// </summary>
        internal static string Log_File {
            get {
                return ResourceManager.GetString("Log File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main menu appears at ähnelt.
        /// </summary>
        internal static string Main_menu_appears_at {
            get {
                return ResourceManager.GetString("Main menu appears at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your root folder for the SystemTrayMenu does not exist or is empty! Put some files, folders or shortcuts into the folder or change the root folder. ähnelt.
        /// </summary>
        internal static string MessageRootFolderEmpty {
            get {
                return ResourceManager.GetString("MessageRootFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have no access to the root folder for the SystemTrayMenu. Grant access to the folder or change the root folder. ähnelt.
        /// </summary>
        internal static string MessageRootFolderNoAccess {
            get {
                return ResourceManager.GetString("MessageRootFolderNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliseconds until a menu opens when the mouse is on it ähnelt.
        /// </summary>
        internal static string Milliseconds_until_a_menu_opens_when_the_mouse_is_on_it {
            get {
                return ResourceManager.GetString("Milliseconds until a menu opens when the mouse is on it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliseconds until the menu closes if in this case the menu is not reactivated ähnelt.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_menu_is_not_reactivated {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the menu is not reactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliseconds until the menu closes if in this case the mouse then leaves the menu ähnelt.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_mouse_then_leaves_the_menu {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the mouse then leaves the menu" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mouse location (Above Taskbar icon) ähnelt.
        /// </summary>
        internal static string Mouse_location__Above_Taskbar_icon_ {
            get {
                return ResourceManager.GetString("Mouse location (Above Taskbar icon)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Files ähnelt.
        /// </summary>
        internal static string Only_Files {
            get {
                return ResourceManager.GetString("Only Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder ähnelt.
        /// </summary>
        internal static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the assembly location ähnelt.
        /// </summary>
        internal static string Open_the_assembly_location {
            get {
                return ResourceManager.GetString("Open the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opened folder ähnelt.
        /// </summary>
        internal static string Opened_folder {
            get {
                return ResourceManager.GetString("Opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels maximum menu height ähnelt.
        /// </summary>
        internal static string Pixels_maximum_menu_height {
            get {
                return ResourceManager.GetString("Pixels maximum menu height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels maximum menu width ähnelt.
        /// </summary>
        internal static string Pixels_maximum_menu_width {
            get {
                return ResourceManager.GetString("Pixels maximum menu width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem with Shortcut ähnelt.
        /// </summary>
        internal static string Problem_with_Shortcut {
            get {
                return ResourceManager.GetString("Problem with Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recursive ähnelt.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove folder ähnelt.
        /// </summary>
        internal static string Remove_folder {
            get {
                return ResourceManager.GetString("Remove folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart ähnelt.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round corners ähnelt.
        /// </summary>
        internal static string Round_corners {
            get {
                return ResourceManager.GetString("Round corners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row height in percentage ähnelt.
        /// </summary>
        internal static string Row_height_in_percentage {
            get {
                return ResourceManager.GetString("Row height in percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scrollbar ähnelt.
        /// </summary>
        internal static string Scrollbar {
            get {
                return ResourceManager.GetString("Scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search field ähnelt.
        /// </summary>
        internal static string Search_field {
            get {
                return ResourceManager.GetString("Search field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Folder ähnelt.
        /// </summary>
        internal static string Select_Folder {
            get {
                return ResourceManager.GetString("Select Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected item ähnelt.
        /// </summary>
        internal static string Selected_item {
            get {
                return ResourceManager.GetString("Selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as SystemTrayMenu folder ähnelt.
        /// </summary>
        internal static string Set_as_SystemTrayMenu_folder {
            get {
                return ResourceManager.GetString("Set as SystemTrayMenu folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set by context menu  ähnelt.
        /// </summary>
        internal static string Set_by_context_menu_ {
            get {
                return ResourceManager.GetString("Set by context menu ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show in Taskbar ähnelt.
        /// </summary>
        internal static string Show_in_Taskbar {
            get {
                return ResourceManager.GetString("Show in Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single click to open an item instead of double click ähnelt.
        /// </summary>
        internal static string Single_click_to_start_item {
            get {
                return ResourceManager.GetString("Single click to start item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider ähnelt.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider while dragging ähnelt.
        /// </summary>
        internal static string Slider_while_dragging {
            get {
                return ResourceManager.GetString("Slider while dragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider while mouse hovers 1 ähnelt.
        /// </summary>
        internal static string Slider_while_mouse_hovers_1 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slider while mouse hovers 2 ähnelt.
        /// </summary>
        internal static string Slider_while_mouse_hovers_2 {
            get {
                return ResourceManager.GetString("Slider while mouse hovers 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stays open ähnelt.
        /// </summary>
        internal static string Stays_open {
            get {
                return ResourceManager.GetString("Stays open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store config at the assembly location ähnelt.
        /// </summary>
        internal static string Store_config_at_the_assembly_location {
            get {
                return ResourceManager.GetString("Store config at the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SystemTrayMenu ähnelt.
        /// </summary>
        internal static string SystemTrayMenu {
            get {
                return ResourceManager.GetString("SystemTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task Manger ähnelt.
        /// </summary>
        internal static string Task_Manger {
            get {
                return ResourceManager.GetString("Task Manger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read the FAQ and then choose a root directory for the SystemTrayMenu. ähnelt.
        /// </summary>
        internal static string TextFirstStart {
            get {
                return ResourceManager.GetString("TextFirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly. ähnelt.
        /// </summary>
        internal static string The_item_that_this_shortcut_refers_to_has_been_changed_or_moved__so_this_shortcut_will_no_longer_work_properly_ {
            get {
                return ResourceManager.GetString("The item that this shortcut refers to has been changed or moved, so this shortcut" +
                        " will no longer work properly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time until a menu opens ähnelt.
        /// </summary>
        internal static string Time_until_a_menu_opens {
            get {
                return ResourceManager.GetString("Time until a menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update the position every time the menu opens ähnelt.
        /// </summary>
        internal static string Update_the_position_every_time_the_menu_opens {
            get {
                return ResourceManager.GetString("Update the position every time the menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USB ähnelt.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use icon from folder ähnelt.
        /// </summary>
        internal static string Use_icon_from_folder {
            get {
                return ResourceManager.GetString("Use icon from folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
