//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTrayMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemTrayMenu.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appear at mouse location.
        /// </summary>
        internal static string Appear_at_mouse_location {
            get {
                return ResourceManager.GetString("Appear at mouse location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string buttonDetails {
            get {
                return ResourceManager.GetString("buttonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string buttonSystemInfo {
            get {
                return ResourceManager.GetString("buttonSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        internal static string Change_folder {
            get {
                return ResourceManager.GetString("Change folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to relative folder.
        /// </summary>
        internal static string Change_to_relative_folder {
            get {
                return ResourceManager.GetString("Change to relative folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors Light Mode and Dark Mode.
        /// </summary>
        internal static string Colors_Light_Mode_and_Dark_Mode {
            get {
                return ResourceManager.GetString("Colors Light Mode and Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn’t register the hot key..
        /// </summary>
        internal static string Could_not_register_the_hot_key_ {
            get {
                return ResourceManager.GetString("Could not register the hot key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Dark_Mode {
            get {
                return ResourceManager.GetString("Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode always active.
        /// </summary>
        internal static string Dark_Mode_always_active {
            get {
                return ResourceManager.GetString("Dark Mode always active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Dark Mode.
        /// </summary>
        internal static string Default_Dark_Mode {
            get {
                return ResourceManager.GetString("Default Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Light Mode.
        /// </summary>
        internal static string Default_Light_Mode {
            get {
                return ResourceManager.GetString("Default Light Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder empty.
        /// </summary>
        internal static string Folder_empty {
            get {
                return ResourceManager.GetString("Folder empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder inaccessible.
        /// </summary>
        internal static string Folder_inaccessible {
            get {
                return ResourceManager.GetString("Folder inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / FAQ.
        /// </summary>
        internal static string HelpFAQ {
            get {
                return ResourceManager.GetString("HelpFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        internal static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an item was clicked.
        /// </summary>
        internal static string If_an_item_was_clicked {
            get {
                return ResourceManager.GetString("If an item was clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the focus is lost and if the mouse is still on the menu.
        /// </summary>
        internal static string If_the_focus_is_lost_and_if_the_mouse_is_still_on_the_menu {
            get {
                return ResourceManager.GetString("If the focus is lost and if the mouse is still on the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on startup.
        /// </summary>
        internal static string Launch_on_startup {
            get {
                return ResourceManager.GetString("Launch on startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        internal static string Log_File {
            get {
                return ResourceManager.GetString("Log File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your root folder for the SystemTrayMenu does not exist or is empty! Put some files, folders or shortcuts into the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderEmpty {
            get {
                return ResourceManager.GetString("MessageRootFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to the root folder for the SystemTrayMenu. Grant access to the folder or change the root folder..
        /// </summary>
        internal static string MessageRootFolderNoAccess {
            get {
                return ResourceManager.GetString("MessageRootFolderNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds until a menu opens when the mouse is on it.
        /// </summary>
        internal static string Milliseconds_until_a_menu_opens_when_the_mouse_is_on_it {
            get {
                return ResourceManager.GetString("Milliseconds until a menu opens when the mouse is on it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds until the menu closes if in this case the mouse then leaves the menu.
        /// </summary>
        internal static string Milliseconds_until_the_menu_closes_if_in_this_case_the_mouse_then_leaves_the_menu {
            get {
                return ResourceManager.GetString("Milliseconds until the menu closes if in this case the mouse then leaves the menu" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open assembly location.
        /// </summary>
        internal static string Open_assembly_location {
            get {
                return ResourceManager.GetString("Open the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string Open_folder {
            get {
                return ResourceManager.GetString("Opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder border.
        /// </summary>
        internal static string Open_folder_border {
            get {
                return ResourceManager.GetString("Border of opened folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels maximum menu width.
        /// </summary>
        internal static string Pixels_maximum_menu_width {
            get {
                return ResourceManager.GetString("Pixels maximum menu width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search field.
        /// </summary>
        internal static string Search_field {
            get {
                return ResourceManager.GetString("Search field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string Select_Folder {
            get {
                return ResourceManager.GetString("Select Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item.
        /// </summary>
        internal static string Selected_item {
            get {
                return ResourceManager.GetString("Selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item border.
        /// </summary>
        internal static string Selected_item_border {
            get {
                return ResourceManager.GetString("Border of selected item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click to open an item.
        /// </summary>
        internal static string Single_click_to_start_item {
            get {
                return ResourceManager.GetString("Single click to start item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and location.
        /// </summary>
        internal static string Size_and_location {
            get {
                return ResourceManager.GetString("Size and location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stays open.
        /// </summary>
        internal static string Stays_open {
            get {
                return ResourceManager.GetString("Stays open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store config at assembly location.
        /// </summary>
        internal static string Store_config_at_assembly_location {
            get {
                return ResourceManager.GetString("Store config at the assembly location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTrayMenu.
        /// </summary>
        internal static string SystemTrayMenu {
            get {
                return ResourceManager.GetString("SystemTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the FAQ and then choose a root directory for the SystemTrayMenu..
        /// </summary>
        internal static string TextFirstStart {
            get {
                return ResourceManager.GetString("TextFirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until a menu opens.
        /// </summary>
        internal static string Time_until_a_menu_opens {
            get {
                return ResourceManager.GetString("Time until a menu opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change a color paste a HTML Color Code or double click into a field..
        /// </summary>
        internal static string To_change_a_color_paste_a_HTML_Color_Code_or_double_click_into_a_field_ {
            get {
                return ResourceManager.GetString("To change a color paste a HTML Color Code or double click into a field.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
