//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTrayMenu.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool IsUpgraded
        {
            get
            {
                return ((bool)(this["IsUpgraded"]));
            }
            set
            {
                this["IsUpgraded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathDirectory
        {
            get
            {
                return ((string)(this["PathDirectory"]));
            }
            set
            {
                this["PathDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SetFolderByWindowsContextMenu
        {
            get
            {
                return ((bool)(this["SetFolderByWindowsContextMenu"]));
            }
            set
            {
                this["SetFolderByWindowsContextMenu"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SaveLogFileInApplicationDirectory
        {
            get
            {
                return ((bool)(this["SaveLogFileInApplicationDirectory"]));
            }
            set
            {
                this["SaveLogFileInApplicationDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool IsAutostartActivated
        {
            get
            {
                return ((bool)(this["IsAutostartActivated"]));
            }
            set
            {
                this["IsAutostartActivated"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool CheckForUpdates
        {
            get
            {
                return ((bool)(this["CheckForUpdates"]));
            }
            set
            {
                this["CheckForUpdates"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+LWin")]
        public string HotKey
        {
            get
            {
                return ((string)(this["HotKey"]));
            }
            set
            {
                this["HotKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentCultureInfoName
        {
            get
            {
                return ((string)(this["CurrentCultureInfoName"]));
            }
            set
            {
                this["CurrentCultureInfoName"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SizeInPercent
        {
            get
            {
                return ((int)(this["SizeInPercent"]));
            }
            set
            {
                this["SizeInPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IconSizeInPercent
        {
            get
            {
                return ((int)(this["IconSizeInPercent"]));
            }
            set
            {
                this["IconSizeInPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int RowHeighteInPercentageTouch
        {
            get
            {
                return ((int)(this["RowHeighteInPercentageTouch"]));
            }
            set
            {
                this["RowHeighteInPercentageTouch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RowHeighteInPercentage
        {
            get
            {
                return ((int)(this["RowHeighteInPercentage"]));
            }
            set
            {
                this["RowHeighteInPercentage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WidthMaxInPercent
        {
            get
            {
                return ((int)(this["WidthMaxInPercent"]));
            }
            set
            {
                this["WidthMaxInPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int HeightMaxInPercent
        {
            get
            {
                return ((int)(this["HeightMaxInPercent"]));
            }
            set
            {
                this["HeightMaxInPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool AppearAtTheBottomLeft
        {
            get
            {
                return ((bool)(this["AppearAtTheBottomLeft"]));
            }
            set
            {
                this["AppearAtTheBottomLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool UseCustomLocation
        {
            get
            {
                return ((bool)(this["UseCustomLocation"]));
            }
            set
            {
                this["UseCustomLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int CustomLocationX
        {
            get
            {
                return ((int)(this["CustomLocationX"]));
            }
            set
            {
                this["CustomLocationX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int CustomLocationY
        {
            get
            {
                return ((int)(this["CustomLocationY"]));
            }
            set
            {
                this["CustomLocationY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool AppearAtMouseLocation
        {
            get
            {
                return ((bool)(this["AppearAtMouseLocation"]));
            }
            set
            {
                this["AppearAtMouseLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool AppearNextToPreviousMenu
        {
            get
            {
                return ((bool)(this["AppearNextToPreviousMenu"]));
            }
            set
            {
                this["AppearNextToPreviousMenu"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int OverlappingOffsetPixels
        {
            get
            {
                return ((int)(this["OverlappingOffsetPixels"]));
            }
            set
            {
                this["OverlappingOffsetPixels"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ResolveLinksToFolders
        {
            get
            {
                return ((bool)(this["ResolveLinksToFolders"]));
            }
            set
            {
                this["ResolveLinksToFolders"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowInTaskbar
        {
            get
            {
                return ((bool)(this["ShowInTaskbar"]));
            }
            set
            {
                this["ShowInTaskbar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SendHotkeyInsteadKillOtherInstances
        {
            get
            {
                return ((bool)(this["SendHotkeyInsteadKillOtherInstances"]));
            }
            set
            {
                this["SendHotkeyInsteadKillOtherInstances"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SupportGamepad
        {
            get
            {
                return ((bool)(this["SupportGamepad"]));
            }
            set
            {
                this["SupportGamepad"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool OpenItemWithOneClick
        {
            get
            {
                return ((bool)(this["OpenItemWithOneClick"]));
            }
            set
            {
                this["OpenItemWithOneClick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool OpenDirectoryWithOneClick
        {
            get
            {
                return ((bool)(this["OpenDirectoryWithOneClick"]));
            }
            set
            {
                this["OpenDirectoryWithOneClick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool DragDropItemsEnabledTouch
        {
            get
            {
                return ((bool)(this["DragDropItemsEnabledTouch"]));
            }
            set
            {
                this["DragDropItemsEnabledTouch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool SwipeScrollingEnabledTouch
        {
            get
            {
                return ((bool)(this["SwipeScrollingEnabledTouch"]));
            }
            set
            {
                this["SwipeScrollingEnabledTouch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool DragDropItemsEnabled
        {
            get
            {
                return ((bool)(this["DragDropItemsEnabled"]));
            }
            set
            {
                this["DragDropItemsEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SwipeScrollingEnabled
        {
            get
            {
                return ((bool)(this["SwipeScrollingEnabled"]));
            }
            set
            {
                this["SwipeScrollingEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathIcoDirectory
        {
            get
            {
                return ((string)(this["PathIcoDirectory"]));
            }
            set
            {
                this["PathIcoDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool SortByTypeAndNameWindowsExplorerSort
        {
            get
            {
                return ((bool)(this["SortByTypeAndNameWindowsExplorerSort"]));
            }
            set
            {
                this["SortByTypeAndNameWindowsExplorerSort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SortByTypeAndDate
        {
            get
            {
                return ((bool)(this["SortByTypeAndDate"]));
            }
            set
            {
                this["SortByTypeAndDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SortByFileExtensionAndName
        {
            get
            {
                return ((bool)(this["SortByFileExtensionAndName"]));
            }
            set
            {
                this["SortByFileExtensionAndName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SortByName
        {
            get
            {
                return ((bool)(this["SortByName"]));
            }
            set
            {
                this["SortByName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SortByDate
        {
            get
            {
                return ((bool)(this["SortByDate"]));
            }
            set
            {
                this["SortByDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool SystemSettingsShowHiddenFiles
        {
            get
            {
                return ((bool)(this["SystemSettingsShowHiddenFiles"]));
            }
            set
            {
                this["SystemSettingsShowHiddenFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool NeverShowHiddenFiles
        {
            get
            {
                return ((bool)(this["NeverShowHiddenFiles"]));
            }
            set
            {
                this["NeverShowHiddenFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool AlwaysShowHiddenFiles
        {
            get
            {
                return ((bool)(this["AlwaysShowHiddenFiles"]));
            }
            set
            {
                this["AlwaysShowHiddenFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool ShowOnlyAsSearchResult
        {
            get
            {
                return ((bool)(this["ShowOnlyAsSearchResult"]));
            }
            set
            {
                this["ShowOnlyAsSearchResult"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathsAddToMainMenu
        {
            get
            {
                return ((string)(this["PathsAddToMainMenu"]));
            }
            set
            {
                this["PathsAddToMainMenu"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool GenerateShortcutsToDrives
        {
            get
            {
                return ((bool)(this["GenerateShortcutsToDrives"]));
            }
            set
            {
                this["GenerateShortcutsToDrives"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TimeUntilOpens
        {
            get
            {
                return ((int)(this["TimeUntilOpens"]));
            }
            set
            {
                this["TimeUntilOpens"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool StaysOpenWhenItemClicked
        {
            get
            {
                return ((bool)(this["StaysOpenWhenItemClicked"]));
            }
            set
            {
                this["StaysOpenWhenItemClicked"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool StaysOpenWhenFocusLost
        {
            get
            {
                return ((bool)(this["StaysOpenWhenFocusLost"]));
            }
            set
            {
                this["StaysOpenWhenFocusLost"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int TimeUntilCloses
        {
            get
            {
                return ((int)(this["TimeUntilCloses"]));
            }
            set
            {
                this["TimeUntilCloses"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool StaysOpenWhenFocusLostAfterEnterPressed
        {
            get
            {
                return ((bool)(this["StaysOpenWhenFocusLostAfterEnterPressed"]));
            }
            set
            {
                this["StaysOpenWhenFocusLostAfterEnterPressed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TimeUntilClosesAfterEnterPressed
        {
            get
            {
                return ((int)(this["TimeUntilClosesAfterEnterPressed"]));
            }
            set
            {
                this["TimeUntilClosesAfterEnterPressed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ClearCacheIfMoreThanThisNumberOfItems
        {
            get
            {
                return ((int)(this["ClearCacheIfMoreThanThisNumberOfItems"]));
            }
            set
            {
                this["ClearCacheIfMoreThanThisNumberOfItems"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchPattern
        {
            get
            {
                return ((string)(this["SearchPattern"]));
            }
            set
            {
                this["SearchPattern"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool UseIconFromRootFolder
        {
            get
            {
                return ((bool)(this["UseIconFromRootFolder"]));
            }
            set
            {
                this["UseIconFromRootFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool RoundCorners
        {
            get
            {
                return ((bool)(this["RoundCorners"]));
            }
            set
            {
                this["RoundCorners"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool IsDarkModeAlwaysOn
        {
            get
            {
                return ((bool)(this["IsDarkModeAlwaysOn"]));
            }
            set
            {
                this["IsDarkModeAlwaysOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool UseFading
        {
            get
            {
                return ((bool)(this["UseFading"]));
            }
            set
            {
                this["UseFading"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool ShowLinkOverlay
        {
            get
            {
                return ((bool)(this["ShowLinkOverlay"]));
            }
            set
            {
                this["ShowLinkOverlay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool ShowDirectoryTitleAtTop
        {
            get
            {
                return ((bool)(this["ShowDirectoryTitleAtTop"]));
            }
            set
            {
                this["ShowDirectoryTitleAtTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowSearchBar
        {
            get
            {
                return ((bool)(this["ShowSearchBar"]));
            }
            set
            {
                this["ShowSearchBar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowFunctionKeyOpenFolder
        {
            get
            {
                return ((bool)(this["ShowFunctionKeyOpenFolder"]));
            }
            set
            {
                this["ShowFunctionKeyOpenFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowFunctionKeyPinMenu
        {
            get
            {
                return ((bool)(this["ShowFunctionKeyPinMenu"]));
            }
            set
            {
                this["ShowFunctionKeyPinMenu"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowFunctionKeySettings
        {
            get
            {
                return ((bool)(this["ShowFunctionKeySettings"]));
            }
            set
            {
                this["ShowFunctionKeySettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowFunctionKeyRestart
        {
            get
            {
                return ((bool)(this["ShowFunctionKeyRestart"]));
            }
            set
            {
                this["ShowFunctionKeyRestart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool ShowCountOfElementsBelow
        {
            get
            {
                return ((bool)(this["ShowCountOfElementsBelow"]));
            }
            set
            {
                this["ShowCountOfElementsBelow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CCE8FF")]
        public string ColorSelectedItem
        {
            get
            {
                return ((string)(this["ColorSelectedItem"]));
            }
            set
            {
                this["ColorSelectedItem"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#333333")]
        public string ColorDarkModeSelecetedItem
        {
            get
            {
                return ((string)(this["ColorDarkModeSelecetedItem"]));
            }
            set
            {
                this["ColorDarkModeSelecetedItem"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99D1FF")]
        public string ColorSelectedItemBorder
        {
            get
            {
                return ((string)(this["ColorSelectedItemBorder"]));
            }
            set
            {
                this["ColorSelectedItemBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#141D4B")]
        public string ColorDarkModeSelectedItemBorder
        {
            get
            {
                return ((string)(this["ColorDarkModeSelectedItemBorder"]));
            }
            set
            {
                this["ColorDarkModeSelectedItemBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#C2F5DE")]
        public string ColorOpenFolder
        {
            get
            {
                return ((string)(this["ColorOpenFolder"]));
            }
            set
            {
                this["ColorOpenFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#14412A")]
        public string ColorDarkModeOpenFolder
        {
            get
            {
                return ((string)(this["ColorDarkModeOpenFolder"]));
            }
            set
            {
                this["ColorDarkModeOpenFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99FFA5")]
        public string ColorOpenFolderBorder
        {
            get
            {
                return ((string)(this["ColorOpenFolderBorder"]));
            }
            set
            {
                this["ColorOpenFolderBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#144B55")]
        public string ColorDarkModeOpenFolderBorder
        {
            get
            {
                return ((string)(this["ColorDarkModeOpenFolderBorder"]));
            }
            set
            {
                this["ColorDarkModeOpenFolderBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorSearchField
        {
            get
            {
                return ((string)(this["ColorSearchField"]));
            }
            set
            {
                this["ColorSearchField"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#191919")]
        public string ColorDarkModeSearchField
        {
            get
            {
                return ((string)(this["ColorDarkModeSearchField"]));
            }
            set
            {
                this["ColorDarkModeSearchField"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorBackground
        {
            get
            {
                return ((string)(this["ColorBackground"]));
            }
            set
            {
                this["ColorBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#202020")]
        public string ColorDarkModeBackground
        {
            get
            {
                return ((string)(this["ColorDarkModeBackground"]));
            }
            set
            {
                this["ColorDarkModeBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorBackgroundBorder
        {
            get
            {
                return ((string)(this["ColorBackgroundBorder"]));
            }
            set
            {
                this["ColorBackgroundBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorDarkModeBackgroundBorder
        {
            get
            {
                return ((string)(this["ColorDarkModeBackgroundBorder"]));
            }
            set
            {
                this["ColorDarkModeBackgroundBorder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606060")]
        public string ColorArrow
        {
            get
            {
                return ((string)(this["ColorArrow"]));
            }
            set
            {
                this["ColorArrow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dadada")]
        public string ColorArrowHoverBackground
        {
            get
            {
                return ((string)(this["ColorArrowHoverBackground"]));
            }
            set
            {
                this["ColorArrowHoverBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorArrowHover
        {
            get
            {
                return ((string)(this["ColorArrowHover"]));
            }
            set
            {
                this["ColorArrowHover"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorArrowClick
        {
            get
            {
                return ((string)(this["ColorArrowClick"]));
            }
            set
            {
                this["ColorArrowClick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606060")]
        public string ColorArrowClickBackground
        {
            get
            {
                return ((string)(this["ColorArrowClickBackground"]));
            }
            set
            {
                this["ColorArrowClickBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#c0c0c0")]
        public string ColorSliderArrowsAndTrackHover
        {
            get
            {
                return ((string)(this["ColorSliderArrowsAndTrackHover"]));
            }
            set
            {
                this["ColorSliderArrowsAndTrackHover"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#cdcdcd")]
        public string ColorSlider
        {
            get
            {
                return ((string)(this["ColorSlider"]));
            }
            set
            {
                this["ColorSlider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#a6a6a6")]
        public string ColorSliderHover
        {
            get
            {
                return ((string)(this["ColorSliderHover"]));
            }
            set
            {
                this["ColorSliderHover"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606060")]
        public string ColorSliderDragging
        {
            get
            {
                return ((string)(this["ColorSliderDragging"]));
            }
            set
            {
                this["ColorSliderDragging"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f0f0f0")]
        public string ColorScrollbarBackground
        {
            get
            {
                return ((string)(this["ColorScrollbarBackground"]));
            }
            set
            {
                this["ColorScrollbarBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#676767")]
        public string ColorArrowDarkMode
        {
            get
            {
                return ((string)(this["ColorArrowDarkMode"]));
            }
            set
            {
                this["ColorArrowDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#373737")]
        public string ColorArrowHoverBackgroundDarkMode
        {
            get
            {
                return ((string)(this["ColorArrowHoverBackgroundDarkMode"]));
            }
            set
            {
                this["ColorArrowHoverBackgroundDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#676767")]
        public string ColorArrowHoverDarkMode
        {
            get
            {
                return ((string)(this["ColorArrowHoverDarkMode"]));
            }
            set
            {
                this["ColorArrowHoverDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#171717")]
        public string ColorArrowClickDarkMode
        {
            get
            {
                return ((string)(this["ColorArrowClickDarkMode"]));
            }
            set
            {
                this["ColorArrowClickDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#a6a6a6")]
        public string ColorArrowClickBackgroundDarkMode
        {
            get
            {
                return ((string)(this["ColorArrowClickBackgroundDarkMode"]));
            }
            set
            {
                this["ColorArrowClickBackgroundDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4d4d4d")]
        public string ColorSliderArrowsAndTrackHoverDarkMode
        {
            get
            {
                return ((string)(this["ColorSliderArrowsAndTrackHoverDarkMode"]));
            }
            set
            {
                this["ColorSliderArrowsAndTrackHoverDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4d4d4d")]
        public string ColorSliderDarkMode
        {
            get
            {
                return ((string)(this["ColorSliderDarkMode"]));
            }
            set
            {
                this["ColorSliderDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7a7a7a")]
        public string ColorSliderHoverDarkMode
        {
            get
            {
                return ((string)(this["ColorSliderHoverDarkMode"]));
            }
            set
            {
                this["ColorSliderHoverDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#a6a6a6")]
        public string ColorSliderDraggingDarkMode
        {
            get
            {
                return ((string)(this["ColorSliderDraggingDarkMode"]));
            }
            set
            {
                this["ColorSliderDraggingDarkMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#171717")]
        public string ColorScrollbarBackgroundDarkMode
        {
            get
            {
                return ((string)(this["ColorScrollbarBackgroundDarkMode"]));
            }
            set
            {
                this["ColorScrollbarBackgroundDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#95a0a6")]
        public string ColorIcons
        {
            get
            {
                return ((string)(this["ColorIcons"]));
            }
            set
            {
                this["ColorIcons"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#95a0a6")]
        public string ColorDarkModeIcons
        {
            get
            {
                return ((string)(this["ColorDarkModeIcons"]));
            }
            set
            {
                this["ColorDarkModeIcons"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool ShowHintYouCanOpenSettingsInSystemtrayIconRightClick
        {
            get
            {
                return ((bool)(this["ShowHintYouCanOpenSettingsInSystemtrayIconRightClick"]));
            }
            set
            {
                this["ShowHintYouCanOpenSettingsInSystemtrayIconRightClick"] = value;
            }
        }
    }
}
